const githubResult = """
  {
    "total_count": 35921,
    "incomplete_results": false,
    "items": [
      {
        "login": "erik",
        "id": 188935,
        "node_id": "MDQ6VXNlcjE4ODkzNQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/188935?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erik",
        "html_url": "https://github.com/erik",
        "followers_url": "https://api.github.com/users/erik/followers",
        "following_url": "https://api.github.com/users/erik/following{/other_user}",
        "gists_url": "https://api.github.com/users/erik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erik/subscriptions",
        "organizations_url": "https://api.github.com/users/erik/orgs",
        "repos_url": "https://api.github.com/users/erik/repos",
        "events_url": "https://api.github.com/users/erik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erik/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikras",
        "id": 4396759,
        "node_id": "MDQ6VXNlcjQzOTY3NTk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4396759?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikras",
        "html_url": "https://github.com/erikras",
        "followers_url": "https://api.github.com/users/erikras/followers",
        "following_url": "https://api.github.com/users/erikras/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikras/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikras/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikras/subscriptions",
        "organizations_url": "https://api.github.com/users/erikras/orgs",
        "repos_url": "https://api.github.com/users/erikras/repos",
        "events_url": "https://api.github.com/users/erikras/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikras/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "eriklindernoren",
        "id": 7977505,
        "node_id": "MDQ6VXNlcjc5Nzc1MDU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7977505?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eriklindernoren",
        "html_url": "https://github.com/eriklindernoren",
        "followers_url": "https://api.github.com/users/eriklindernoren/followers",
        "following_url": "https://api.github.com/users/eriklindernoren/following{/other_user}",
        "gists_url": "https://api.github.com/users/eriklindernoren/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eriklindernoren/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eriklindernoren/subscriptions",
        "organizations_url": "https://api.github.com/users/eriklindernoren/orgs",
        "repos_url": "https://api.github.com/users/eriklindernoren/repos",
        "events_url": "https://api.github.com/users/eriklindernoren/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eriklindernoren/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ErikCH",
        "id": 65630,
        "node_id": "MDQ6VXNlcjY1NjMw",
        "avatar_url": "https://avatars.githubusercontent.com/u/65630?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikCH",
        "html_url": "https://github.com/ErikCH",
        "followers_url": "https://api.github.com/users/ErikCH/followers",
        "following_url": "https://api.github.com/users/ErikCH/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikCH/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikCH/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikCH/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikCH/orgs",
        "repos_url": "https://api.github.com/users/ErikCH/repos",
        "events_url": "https://api.github.com/users/ErikCH/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikCH/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikbern",
        "id": 1027979,
        "node_id": "MDQ6VXNlcjEwMjc5Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1027979?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikbern",
        "html_url": "https://github.com/erikbern",
        "followers_url": "https://api.github.com/users/erikbern/followers",
        "following_url": "https://api.github.com/users/erikbern/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikbern/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikbern/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikbern/subscriptions",
        "organizations_url": "https://api.github.com/users/erikbern/orgs",
        "repos_url": "https://api.github.com/users/erikbern/repos",
        "events_url": "https://api.github.com/users/erikbern/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikbern/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikaheidi",
        "id": 293241,
        "node_id": "MDQ6VXNlcjI5MzI0MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/293241?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikaheidi",
        "html_url": "https://github.com/erikaheidi",
        "followers_url": "https://api.github.com/users/erikaheidi/followers",
        "following_url": "https://api.github.com/users/erikaheidi/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikaheidi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikaheidi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikaheidi/subscriptions",
        "organizations_url": "https://api.github.com/users/erikaheidi/orgs",
        "repos_url": "https://api.github.com/users/erikaheidi/repos",
        "events_url": "https://api.github.com/users/erikaheidi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikaheidi/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikdubois",
        "id": 10594806,
        "node_id": "MDQ6VXNlcjEwNTk0ODA2",
        "avatar_url": "https://avatars.githubusercontent.com/u/10594806?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikdubois",
        "html_url": "https://github.com/erikdubois",
        "followers_url": "https://api.github.com/users/erikdubois/followers",
        "following_url": "https://api.github.com/users/erikdubois/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikdubois/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikdubois/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikdubois/subscriptions",
        "organizations_url": "https://api.github.com/users/erikdubois/orgs",
        "repos_url": "https://api.github.com/users/erikdubois/repos",
        "events_url": "https://api.github.com/users/erikdubois/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikdubois/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ErikEJ",
        "id": 4169187,
        "node_id": "MDQ6VXNlcjQxNjkxODc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4169187?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikEJ",
        "html_url": "https://github.com/ErikEJ",
        "followers_url": "https://api.github.com/users/ErikEJ/followers",
        "following_url": "https://api.github.com/users/ErikEJ/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikEJ/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikEJ/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikEJ/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikEJ/orgs",
        "repos_url": "https://api.github.com/users/ErikEJ/repos",
        "events_url": "https://api.github.com/users/ErikEJ/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikEJ/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "errorrik",
        "id": 2851010,
        "node_id": "MDQ6VXNlcjI4NTEwMTA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2851010?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/errorrik",
        "html_url": "https://github.com/errorrik",
        "followers_url": "https://api.github.com/users/errorrik/followers",
        "following_url": "https://api.github.com/users/errorrik/following{/other_user}",
        "gists_url": "https://api.github.com/users/errorrik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/errorrik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/errorrik/subscriptions",
        "organizations_url": "https://api.github.com/users/errorrik/orgs",
        "repos_url": "https://api.github.com/users/errorrik/repos",
        "events_url": "https://api.github.com/users/errorrik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/errorrik/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "eriktrautman",
        "id": 2977438,
        "node_id": "MDQ6VXNlcjI5Nzc0Mzg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2977438?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eriktrautman",
        "html_url": "https://github.com/eriktrautman",
        "followers_url": "https://api.github.com/users/eriktrautman/followers",
        "following_url": "https://api.github.com/users/eriktrautman/following{/other_user}",
        "gists_url": "https://api.github.com/users/eriktrautman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eriktrautman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eriktrautman/subscriptions",
        "organizations_url": "https://api.github.com/users/eriktrautman/orgs",
        "repos_url": "https://api.github.com/users/eriktrautman/repos",
        "events_url": "https://api.github.com/users/eriktrautman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eriktrautman/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ErikHellman",
        "id": 72444,
        "node_id": "MDQ6VXNlcjcyNDQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/72444?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikHellman",
        "html_url": "https://github.com/ErikHellman",
        "followers_url": "https://api.github.com/users/ErikHellman/followers",
        "following_url": "https://api.github.com/users/ErikHellman/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikHellman/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikHellman/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikHellman/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikHellman/orgs",
        "repos_url": "https://api.github.com/users/ErikHellman/repos",
        "events_url": "https://api.github.com/users/ErikHellman/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikHellman/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ErikSchierboom",
        "id": 135246,
        "node_id": "MDQ6VXNlcjEzNTI0Ng==",
        "avatar_url": "https://avatars.githubusercontent.com/u/135246?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikSchierboom",
        "html_url": "https://github.com/ErikSchierboom",
        "followers_url": "https://api.github.com/users/ErikSchierboom/followers",
        "following_url": "https://api.github.com/users/ErikSchierboom/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikSchierboom/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikSchierboom/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikSchierboom/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikSchierboom/orgs",
        "repos_url": "https://api.github.com/users/ErikSchierboom/repos",
        "events_url": "https://api.github.com/users/ErikSchierboom/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikSchierboom/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikrose",
        "id": 295816,
        "node_id": "MDQ6VXNlcjI5NTgxNg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/295816?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikrose",
        "html_url": "https://github.com/erikrose",
        "followers_url": "https://api.github.com/users/erikrose/followers",
        "following_url": "https://api.github.com/users/erikrose/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikrose/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikrose/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikrose/subscriptions",
        "organizations_url": "https://api.github.com/users/erikrose/orgs",
        "repos_url": "https://api.github.com/users/erikrose/repos",
        "events_url": "https://api.github.com/users/erikrose/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikrose/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikvold",
        "id": 27379,
        "node_id": "MDQ6VXNlcjI3Mzc5",
        "avatar_url": "https://avatars.githubusercontent.com/u/27379?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikvold",
        "html_url": "https://github.com/erikvold",
        "followers_url": "https://api.github.com/users/erikvold/followers",
        "following_url": "https://api.github.com/users/erikvold/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikvold/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikvold/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikvold/subscriptions",
        "organizations_url": "https://api.github.com/users/erikvold/orgs",
        "repos_url": "https://api.github.com/users/erikvold/repos",
        "events_url": "https://api.github.com/users/erikvold/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikvold/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erik168",
        "id": 696441,
        "node_id": "MDQ6VXNlcjY5NjQ0MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/696441?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erik168",
        "html_url": "https://github.com/erik168",
        "followers_url": "https://api.github.com/users/erik168/followers",
        "following_url": "https://api.github.com/users/erik168/following{/other_user}",
        "gists_url": "https://api.github.com/users/erik168/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erik168/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erik168/subscriptions",
        "organizations_url": "https://api.github.com/users/erik168/orgs",
        "repos_url": "https://api.github.com/users/erik168/repos",
        "events_url": "https://api.github.com/users/erik168/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erik168/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikfig",
        "id": 4331013,
        "node_id": "MDQ6VXNlcjQzMzEwMTM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4331013?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikfig",
        "html_url": "https://github.com/erikfig",
        "followers_url": "https://api.github.com/users/erikfig/followers",
        "following_url": "https://api.github.com/users/erikfig/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikfig/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikfig/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikfig/subscriptions",
        "organizations_url": "https://api.github.com/users/erikfig/orgs",
        "repos_url": "https://api.github.com/users/erikfig/repos",
        "events_url": "https://api.github.com/users/erikfig/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikfig/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikd",
        "id": 307277,
        "node_id": "MDQ6VXNlcjMwNzI3Nw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/307277?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikd",
        "html_url": "https://github.com/erikd",
        "followers_url": "https://api.github.com/users/erikd/followers",
        "following_url": "https://api.github.com/users/erikd/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikd/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikd/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikd/subscriptions",
        "organizations_url": "https://api.github.com/users/erikd/orgs",
        "repos_url": "https://api.github.com/users/erikd/repos",
        "events_url": "https://api.github.com/users/erikd/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikd/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ErikBjare",
        "id": 1405370,
        "node_id": "MDQ6VXNlcjE0MDUzNzA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1405370?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikBjare",
        "html_url": "https://github.com/ErikBjare",
        "followers_url": "https://api.github.com/users/ErikBjare/followers",
        "following_url": "https://api.github.com/users/ErikBjare/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikBjare/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikBjare/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikBjare/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikBjare/orgs",
        "repos_url": "https://api.github.com/users/ErikBjare/repos",
        "events_url": "https://api.github.com/users/ErikBjare/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikBjare/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "eriksvedang",
        "id": 356121,
        "node_id": "MDQ6VXNlcjM1NjEyMQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/356121?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eriksvedang",
        "html_url": "https://github.com/eriksvedang",
        "followers_url": "https://api.github.com/users/eriksvedang/followers",
        "following_url": "https://api.github.com/users/eriksvedang/following{/other_user}",
        "gists_url": "https://api.github.com/users/eriksvedang/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eriksvedang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eriksvedang/subscriptions",
        "organizations_url": "https://api.github.com/users/eriksvedang/orgs",
        "repos_url": "https://api.github.com/users/eriksvedang/repos",
        "events_url": "https://api.github.com/users/eriksvedang/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eriksvedang/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikfritas",
        "id": 74334533,
        "node_id": "MDQ6VXNlcjc0MzM0NTMz",
        "avatar_url": "https://avatars.githubusercontent.com/u/74334533?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikfritas",
        "html_url": "https://github.com/erikfritas",
        "followers_url": "https://api.github.com/users/erikfritas/followers",
        "following_url": "https://api.github.com/users/erikfritas/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikfritas/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikfritas/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikfritas/subscriptions",
        "organizations_url": "https://api.github.com/users/erikfritas/orgs",
        "repos_url": "https://api.github.com/users/erikfritas/repos",
        "events_url": "https://api.github.com/users/erikfritas/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikfritas/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erik-nelson",
        "id": 2200159,
        "node_id": "MDQ6VXNlcjIyMDAxNTk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2200159?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erik-nelson",
        "html_url": "https://github.com/erik-nelson",
        "followers_url": "https://api.github.com/users/erik-nelson/followers",
        "following_url": "https://api.github.com/users/erik-nelson/following{/other_user}",
        "gists_url": "https://api.github.com/users/erik-nelson/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erik-nelson/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erik-nelson/subscriptions",
        "organizations_url": "https://api.github.com/users/erik-nelson/orgs",
        "repos_url": "https://api.github.com/users/erik-nelson/repos",
        "events_url": "https://api.github.com/users/erik-nelson/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erik-nelson/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikdubbelboer",
        "id": 522870,
        "node_id": "MDQ6VXNlcjUyMjg3MA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/522870?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikdubbelboer",
        "html_url": "https://github.com/erikdubbelboer",
        "followers_url": "https://api.github.com/users/erikdubbelboer/followers",
        "following_url": "https://api.github.com/users/erikdubbelboer/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikdubbelboer/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikdubbelboer/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikdubbelboer/subscriptions",
        "organizations_url": "https://api.github.com/users/erikdubbelboer/orgs",
        "repos_url": "https://api.github.com/users/erikdubbelboer/repos",
        "events_url": "https://api.github.com/users/erikdubbelboer/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikdubbelboer/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ErikBoesen",
        "id": 5923662,
        "node_id": "MDQ6VXNlcjU5MjM2NjI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5923662?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ErikBoesen",
        "html_url": "https://github.com/ErikBoesen",
        "followers_url": "https://api.github.com/users/ErikBoesen/followers",
        "following_url": "https://api.github.com/users/ErikBoesen/following{/other_user}",
        "gists_url": "https://api.github.com/users/ErikBoesen/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ErikBoesen/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ErikBoesen/subscriptions",
        "organizations_url": "https://api.github.com/users/ErikBoesen/orgs",
        "repos_url": "https://api.github.com/users/ErikBoesen/repos",
        "events_url": "https://api.github.com/users/ErikBoesen/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ErikBoesen/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "sferik",
        "id": 10308,
        "node_id": "MDQ6VXNlcjEwMzA4",
        "avatar_url": "https://avatars.githubusercontent.com/u/10308?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sferik",
        "html_url": "https://github.com/sferik",
        "followers_url": "https://api.github.com/users/sferik/followers",
        "following_url": "https://api.github.com/users/sferik/following{/other_user}",
        "gists_url": "https://api.github.com/users/sferik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sferik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sferik/subscriptions",
        "organizations_url": "https://api.github.com/users/sferik/orgs",
        "repos_url": "https://api.github.com/users/sferik/repos",
        "events_url": "https://api.github.com/users/sferik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sferik/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "rigtorp",
        "id": 178027,
        "node_id": "MDQ6VXNlcjE3ODAyNw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/178027?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rigtorp",
        "html_url": "https://github.com/rigtorp",
        "followers_url": "https://api.github.com/users/rigtorp/followers",
        "following_url": "https://api.github.com/users/rigtorp/following{/other_user}",
        "gists_url": "https://api.github.com/users/rigtorp/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rigtorp/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rigtorp/subscriptions",
        "organizations_url": "https://api.github.com/users/rigtorp/orgs",
        "repos_url": "https://api.github.com/users/rigtorp/repos",
        "events_url": "https://api.github.com/users/rigtorp/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rigtorp/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikh",
        "id": 18923,
        "node_id": "MDQ6VXNlcjE4OTIz",
        "avatar_url": "https://avatars.githubusercontent.com/u/18923?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikh",
        "html_url": "https://github.com/erikh",
        "followers_url": "https://api.github.com/users/erikh/followers",
        "following_url": "https://api.github.com/users/erikh/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikh/subscriptions",
        "organizations_url": "https://api.github.com/users/erikh/orgs",
        "repos_url": "https://api.github.com/users/erikh/repos",
        "events_url": "https://api.github.com/users/erikh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikh/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "yarwelp",
        "id": 385688,
        "node_id": "MDQ6VXNlcjM4NTY4OA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/385688?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/yarwelp",
        "html_url": "https://github.com/yarwelp",
        "followers_url": "https://api.github.com/users/yarwelp/followers",
        "following_url": "https://api.github.com/users/yarwelp/following{/other_user}",
        "gists_url": "https://api.github.com/users/yarwelp/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/yarwelp/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/yarwelp/subscriptions",
        "organizations_url": "https://api.github.com/users/yarwelp/orgs",
        "repos_url": "https://api.github.com/users/yarwelp/repos",
        "events_url": "https://api.github.com/users/yarwelp/events{/privacy}",
        "received_events_url": "https://api.github.com/users/yarwelp/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "edemaine",
        "id": 2218736,
        "node_id": "MDQ6VXNlcjIyMTg3MzY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2218736?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/edemaine",
        "html_url": "https://github.com/edemaine",
        "followers_url": "https://api.github.com/users/edemaine/followers",
        "following_url": "https://api.github.com/users/edemaine/following{/other_user}",
        "gists_url": "https://api.github.com/users/edemaine/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/edemaine/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/edemaine/subscriptions",
        "organizations_url": "https://api.github.com/users/edemaine/orgs",
        "repos_url": "https://api.github.com/users/edemaine/repos",
        "events_url": "https://api.github.com/users/edemaine/events{/privacy}",
        "received_events_url": "https://api.github.com/users/edemaine/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikjhordan-rey",
        "id": 5893477,
        "node_id": "MDQ6VXNlcjU4OTM0Nzc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5893477?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikjhordan-rey",
        "html_url": "https://github.com/erikjhordan-rey",
        "followers_url": "https://api.github.com/users/erikjhordan-rey/followers",
        "following_url": "https://api.github.com/users/erikjhordan-rey/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikjhordan-rey/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikjhordan-rey/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikjhordan-rey/subscriptions",
        "organizations_url": "https://api.github.com/users/erikjhordan-rey/orgs",
        "repos_url": "https://api.github.com/users/erikjhordan-rey/repos",
        "events_url": "https://api.github.com/users/erikjhordan-rey/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikjhordan-rey/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "erikstmartin",
        "id": 50041,
        "node_id": "MDQ6VXNlcjUwMDQx",
        "avatar_url": "https://avatars.githubusercontent.com/u/50041?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erikstmartin",
        "html_url": "https://github.com/erikstmartin",
        "followers_url": "https://api.github.com/users/erikstmartin/followers",
        "following_url": "https://api.github.com/users/erikstmartin/following{/other_user}",
        "gists_url": "https://api.github.com/users/erikstmartin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erikstmartin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erikstmartin/subscriptions",
        "organizations_url": "https://api.github.com/users/erikstmartin/orgs",
        "repos_url": "https://api.github.com/users/erikstmartin/repos",
        "events_url": "https://api.github.com/users/erikstmartin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erikstmartin/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      }
    ]
  }
""";