// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_clean_architecture/test/modules/search/infra/repositories/search_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_clean_architecture/modules/search/infra/datasources/search_datasource.dart'
    as _i2;
import 'package:flutter_clean_architecture/modules/search/infra/models/result_search_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SearchDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchDatasource extends _i1.Mock implements _i2.SearchDatasource {
  MockSearchDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ResultSearchModel>> getSearch(String? searchText) =>
      (super.noSuchMethod(Invocation.method(#getSearch, [searchText]),
              returnValue: Future<List<_i4.ResultSearchModel>>.value(
                  <_i4.ResultSearchModel>[]))
          as _i3.Future<List<_i4.ResultSearchModel>>);
}
